// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fmivyrlzbyypoytdbrps.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtaXZ5cmx6Ynl5cG95dGRicnBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNjQ1MjgsImV4cCI6MjA2NDc0MDUyOH0.BFfoc5seRNKjKaRQ8WyjrtQtiJDtL2EjW2bfA3CUWtg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);